config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :super_admins,
    controllers: { sessions: 'super_admin/sessions' }
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :admins,
    controllers: { registrations: 'admin/accounts/registrations', sessions: 'admin/accounts/sessions' }
  namespace :admin do
    root 'shop_dashboard#index'
    resources :shop_dashboard do
      collection do
        get '/settings', to: 'shop_dashboard#edit'
      end
    end
    resources :menu_dashboard
    resources :category_dashboard
    resources :cuisine_dashboard
    post '/categories/', to: 'cuisine_dashboard#categories', as: :categories_json
    resources :shop_photo_dashboard
  end

  devise_for :users,
    controllers: { registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      passwords: 'users/passwords',
      unlocks: 'users/unlocks',
      sessions: 'users/sessions' }
  resources :comments, except: [:index, :show]

  namespace :super_admin do
    root 'city_dashboard#index'
    resources :city_dashboard
    resources :shop_dashboard do
      collection do
        patch 'update_plan'
      end
    end
    resources :messages_dashboard
  end

  resources :cities , except: [:show]
  get '/city/:slug', to: 'cities#show'

  resources :restaurants, only: [:index]

  resources :cafes, except: [:show] do
    resources :cuisines, only: [:show]
  end

  resources :confectioneries, only: [:index]

  resources :cafes, only: [:index]

  resources :search, only: [:index]
  get '/:city_slug/restaurant/:shop_slug', to: 'restaurants#show', as: :restaurant_show
  get '/:city_slug/restaurant/:shop_slug/cuisine/:item_slug', to: 'cuisines#show', as: :restaurant_cuisine_show

  get '/:city_slug/confectionery/:shop_slug', to: 'confectioneries#show', as: :confectionery_show
  get '/:city_slug/confectionery/:shop_slug/item/:item_slug', to: 'cuisines#show', as: :confectionery_item_show

  get '/:city_slug/cafe/:shop_slug', to: 'cafes#show', as: :cafe_show
  get '/:city_slug/cafe/:shop_slug/item/:item_slug', to: 'cuisines#show', as: :cafe_item_show


  get '/:city/restaurants', to: 'restaurants#index', as: :cities_restaurants_index
  get '/:city/confectioneries', to: 'confectioneries#index', as: :cities_confectioneries_index
  get '/:city/cafes', to: 'cafes#index', as: :cities_cafes_index

  root 'basic_pages#index'
  get 'about', to: 'basic_pages#about'
  get 'contact', to: 'messages#new'
  resources :messages, only: [:create]

  get '/:slug', to: 'cities#show', as: :city_show
end

app/controllers/admin/cuisine_dashboard_controller.rb
class Admin::CuisineDashboardController < ApplicationController
  before_action :authenticate_admin!

  def index
    @cuisines = current_admin.cuisines
  end

  def new
    @cuisine = Cuisine.new
    @cuisine.photos.build
    @menus = current_admin.menus
  end

  def categories
    categories = current_admin.categories.where("menu_id = ?", params[:menu_id])
    render json: categories
  end

  def create
    @cuisine = Cuisine.new(cuisine_params)
    if current_admin.has_category?(@cuisine.category_id) && @cuisine.save
      redirect_to :back, alert: "Cuisine Addded"
    else
      redirect_to :back, notice: "#{@cuisine.errors.full_messages.join(', ')}"
    end
  end

  def edit
    @cuisine = current_admin.cuisines.where("cuisines.slug = ?", params[:id])
    .first.becomes(Cuisine)
    @categories = current_admin.categories
    @cuisine.photos.build if @cuisine.photos.blank?
  end

  # ISSUE this update is overriding validations
  def update
    @cuisine = current_admin.cuisines.where("cuisines.slug = ?", params[:id]).first.becomes(Cuisine)
    if current_admin.has_category?(@cuisine.category_id) && @cuisine.update(cuisine_params)
      redirect_to :back, alert: "Cuisine Updated"
    else
      redirect_to :back, notice: "#{@cuisine.errors.full_messages.join(', ')}"
    end
  end

  def destroy
    cuisine = Cuisine.find(params[:id])
    if cuisine.category.menu.shop.admin == current_admin && cuisine.destroy
      redirect_to :back, alert: "Cuisine Destroyed"
    else
      redirect_to :back, notice: "#{cuisine.errors.full_messages.join(', ')}"
    end
  end

  private

  def cuisine_params
    params.require(:cuisine).permit(:name, :category_id, :price, :description,
    :ingredient, :vegetarian, photos_attributes: [:id, :image, :_destroy])
  end
end

app/views/admin/cuisine_dashboard/edit.html.slim
.container-fluid
  .row
    .col-md-12
      h1 Dashboard
  .row
    .col-md-2
      == render "admin/dashboard_menu"
    .col-md-10
      /! Nav tabs
      ul.nav.nav-tabs role="tablist" 
        li role="presentation" 
          = link_to "Cusines", admin_cuisine_dashboard_index_path,
          data: { toggle: "tooltip", placement: "top"}, title: "View all Cuisines"
        li role="presentation" 
          = link_to "Add Cusine", new_admin_cuisine_dashboard_path,
          data: { toggle: "tooltip", placement: "top"}, title: "Add new Cuisines"
        li.active role="presentation" 
          = link_to "Edit Cusine", edit_admin_cuisine_dashboard_path(@cuisine)
      /! Tab panes
      .tab-content
        h2 Edit Cuisine/Item
        = form_for @cuisine, url: admin_cuisine_dashboard_path(@cuisine), method: :patch do |f|
          .form-group
            = f.label :category
            = f.select :category_id, @categories.collect { |cat| [cat.name, cat.id]}, {}, { class: "form-control" }
          .form-group
            = f.label :name
            = f.text_field :name, class: "form-control", required: true
          .checkbox
            label
              = f.check_box :vegetarian
              | Vegetarain
          .form-group
            = f.label :description
            = f.bootsy_area :description, editor_options: { image: false },
              class: "form-control", required: true, rows: "20"
          .form-group
            = f.label :ingredient, "Ingredients"
            = f.bootsy_area :ingredient, editor_options: { image: false },
              class: "form-control", required: true, rows: "5"
            i.text-muted Pleases use comma to separate each ingredient
          .form-group
            = f.label :price
            = f.text_field :price, class: "form-control", required: true
          - if @cuisine.photos.count > 0
            = f.fields_for :photos do |photo_form|
              .row
                .form-group.col-md-4.text-center
                  = image_tag photo_form.object.image_url(:thumb)
                  br
                  .check_box
                    label
                      => photo_form.check_box :_destroy
                      | Destroy
          - else
            = f.fields_for :photos do |photo|
              .form-group
                = photo.label :image
                = photo.file_field :image, class: "form-control"
          .form-group
            = f.submit "Save", class: "btn btn-primary"

app/views/admin/cuisine_dashboard/index.html.slim
.container-fluid
  .row
    .col-md-12
      h1 Dashboard
  .row
    .col-md-2
      == render "admin/dashboard_menu"
    .col-md-10
      /! Nav tabs
      ul.nav.nav-tabs role="tablist" 
        li.active role="presentation" 
          = link_to "Cuisine", admin_cuisine_dashboard_index_path,
          data: { toggle: "tooltip", placement: "top"}, title: "View all Cuisines"
        li role="presentation" 
          = link_to "Add Cusine", new_admin_cuisine_dashboard_path,
          data: { toggle: "tooltip", placement: "top"}, title: "Add new Cuisine"
      /! Tab panes
      .tab-content
        h2 Cuisines/Items
        table.table
          tr
            th Name
            th Price
            th Category
            th Menu
            th Actions
          - @cuisines.each do |cuisine|
            tr
              td = cuisine.name
              td = cuisine.price 
              td = cuisine.category_name
              td = cuisine.menu_name
              td 
                => link_to "Delete", admin_cuisine_dashboard_path(cuisine.id),
                method: :delete, class: 'btn btn-danger btn-xs',
                data: { confirm: "Are you sure ?" }
                
                => link_to "Edit", edit_admin_cuisine_dashboard_path(cuisine),
                class: 'btn btn-primary btn-xs'

app/views/admin/cuisine_dashboard/new.html.slim
.container-fluid
  .row
    .col-md-12
      h1 Dashboard
  .row
    .col-md-2
      == render "admin/dashboard_menu"
    .col-md-10
      /! Nav tabs
      ul.nav.nav-tabs role="tablist" 
        li role="presentation" 
          = link_to "Cusines", admin_cuisine_dashboard_index_path,
          data: { toggle: "tooltip", placement: "top"}, title: "View all Cuisines"
        li.active role="presentation" 
          = link_to "Add Cusine", new_admin_cuisine_dashboard_path,
          data: { toggle: "tooltip", placement: "top"}, title: "Add new Cuisines"
      /! Tab panes
      .tab-content
        h2 New Cuisine/Item
        = form_for @cuisine, url: admin_cuisine_dashboard_index_path, method: :post do |f|
          .form-group
            = f.label :menu
            = select_tag "menu", options_from_collection_for_select(@menus, "menu_id", "menu_name"),
            include_blank: true, class: "form-control", id: "menu"
          .form-group
            = f.label :category
            = f.select :category_id, [], {}, {class: "form-control"}
          .form-group
            = f.label :name
            = f.text_field :name, class: "form-control", required: true
          .checkbox
            label
              = f.check_box :vegetarian
              | Vegetarain
          .form-group
            = f.label :description
            = f.bootsy_area :description, editor_options: { image: false },
              class: "form-control", required: true, rows: "20"
          .form-group
            = f.label :ingredient, "Ingredients"
            = f.bootsy_area :ingredient, editor_options: { image: false },
              class: "form-control", required: true, rows: "5"
            i.text-muted "Pleases use comma to separate each ingredient"
          .form-group
            = f.label :price
            = f.text_field :price, class: "form-control", required: true
          = f.fields_for :photos do |photo_form|
            .form-group
              = photo_form.label :image
              = photo_form.file_field :image, class: "form-control", required: true
          .form-group
            = f.submit "Save", class: "btn btn-primary"

coffee:
  $("#menu").on 'change', () ->
    $.ajax {
      url: '/admin/categories',
      method: 'post',
      data: { menu_id: $("#menu").val() }
    }
    .done (data) ->
      $("#cuisine_category_id").html("")
      jQuery.each data, (key, val) ->
        $("#cuisine_category_id").append("<option value='" + val.id + "'>" + val.name + "</option>")