config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :super_admins,
    controllers: { sessions: 'super_admin/sessions' }
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :admins,
    controllers: { registrations: 'admin/accounts/registrations', sessions: 'admin/accounts/sessions' }
  namespace :admin do
    root 'shop_dashboard#index'
    resources :shop_dashboard do
      collection do
        get '/settings', to: 'shop_dashboard#edit'
      end
    end
    resources :menu_dashboard
    resources :category_dashboard
    resources :cuisine_dashboard
    post '/categories/', to: 'cuisine_dashboard#categories', as: :categories_json
    resources :shop_photo_dashboard
  end

  devise_for :users,
    controllers: { registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      passwords: 'users/passwords',
      unlocks: 'users/unlocks',
      sessions: 'users/sessions' }
  resources :comments, except: [:index, :show]

  namespace :super_admin do
    root 'city_dashboard#index'
    resources :city_dashboard
    resources :shop_dashboard do
      collection do
        patch 'update_plan'
      end
    end
    resources :messages_dashboard
  end

  resources :cities , except: [:show]
  get '/city/:slug', to: 'cities#show'

  resources :restaurants, only: [:index]

  resources :cafes, except: [:show] do
    resources :cuisines, only: [:show]
  end

  resources :confectioneries, only: [:index]

  resources :cafes, only: [:index]

  resources :search, only: [:index]
  get '/:city_slug/restaurant/:shop_slug', to: 'restaurants#show', as: :restaurant_show
  get '/:city_slug/restaurant/:shop_slug/cuisine/:item_slug', to: 'cuisines#show', as: :restaurant_cuisine_show

  get '/:city_slug/confectionery/:shop_slug', to: 'confectioneries#show', as: :confectionery_show
  get '/:city_slug/confectionery/:shop_slug/item/:item_slug', to: 'cuisines#show', as: :confectionery_item_show

  get '/:city_slug/cafe/:shop_slug', to: 'cafes#show', as: :cafe_show
  get '/:city_slug/cafe/:shop_slug/item/:item_slug', to: 'cuisines#show', as: :cafe_item_show


  get '/:city/restaurants', to: 'restaurants#index', as: :cities_restaurants_index
  get '/:city/confectioneries', to: 'confectioneries#index', as: :cities_confectioneries_index
  get '/:city/cafes', to: 'cafes#index', as: :cities_cafes_index

  root 'basic_pages#index'
  get 'about', to: 'basic_pages#about'
  get 'contact', to: 'messages#new'
  resources :messages, only: [:create]

  get '/:slug', to: 'cities#show', as: :city_show
end

app/controllers/basic_pages_controller.rb
class BasicPagesController < ApplicationController
  def index
    @cities = City.joins(:shops).group('cities.id').order('name')
  end

  def about
  end

  def contact
  end
end

app/helpers/basic_pages_helper.rb
module BasicPagesHelper
end

app/views/basic_pages/about.html.slim
.container-fluid
  .row
    .col-md-offset-2.col-md-8.text-center
      h1 About us
  .row
    .col-md-offset-2.col-md-8.text-center
      | We are really passionate people we love food and want people to have the best food available. Our mission is to bring the food bazar to your pocket.
  .row
    .col-md-offset-2.col-md-8.text-center
      h2  Our Team
      .text-center Comming Soon..

app/views/basic_pages/contact.html.slim
.container-fluid
  .row
    .col-md-offset-2.col-md-8.text-center
      h1 Contact
  .row
    .col-md-offset-2.col-md-8.text-center
      ' Please drop us an email at
      = link_to "support@bhukaad.com", "mailto:support@bhukaad.com"

app/views/basic_pages/index.html.slim
.container-fluid
  .row
    .col-sm-12.col-md-8.col-md-offset-2
      header.text-center.main-header
        h1 Feeling Hungry ?
        p Find a restaurant or cafe to refuel yourself.
        .container-fluid
          .row
            .col-xs-12
              = form_tag '/search', method: :get do
                .input-group
                  = text_field_tag :q, nil, class: "form-control bku-search-field"
                  span.input-group-btn
                    = submit_tag "Go", class: "btn btn-default"
  .separator-md-medium
  .row
    .col-sm-12.col-md-8.col-md-offset-2
      .container-fluid
        .row
          .col-xs-12.col-sm-4
            .tile
              .overlay
                = link_to "Restaurants", restaurants_path
              .bak-tile.restaurant-tile
          .col-xs-12.col-sm-4
            .tile
              .overlay 
                = link_to "Cafes", cafes_path
              .bak-tile.cafe-tile
          .col-xs-12.col-sm-4
            .tile
              .overlay 
                = link_to "Confectioneries", confectioneries_path
              .bak-tile.confectionery-tile
#cityModal.modal.fade.bs-example-modal-sm aria-labelledby="mySmallModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
        h4#myModalLabel.modal-title Select your City
      .modal-body
        = select_tag :city, options_from_collection_for_select(@cities, "slug", "name"), include_blank: true, class: "form-control"
coffee:
  $("#cityModal").modal()
  $("#city").on 'change', () ->
    city_name = $(this).val()
    window.location.href = "/" + city_name
    